### ISSUE TITLE
Support .dockerignore

### ISSUE THREAD

**Issue by thefotios-enigma** [toptal/gitignore.io#415]
First off, awesome project! I use it on every repo and it's made my life (and my teams' lives so much better).

Since you have such a good collection of what should be ignored for each language/framework/etc, have you ever thought about expanding it to `.dockerignore` files as well? The syntax is slightly different, but it could be really useful.

I could see this working 2 ways:
 - Extend https://www.github.com/dvcs/gitignore to include the equivalent `.dockerignore` (and `.patch`) files and serve them here as well.
 - Automatically convert the final rendered `.gitignore` files to `.dockerignore` format (with things like prepending `**` to directories).
    - This might be tricky because there are cases where there isn't 100% parity. For instance, you commit `.rc` type files for linters, tools, etc or test folders to git, but you generally don't want to include them in your containers.

**Comment by joeblau** [comment]
Thanks for the kind words.  I haven't really through about creating `.dockerignore`, but that sounds like it would be a great addition.

One of the projects I want to work on is extracting the template generation engine into it's own project.  With the guts of what generates its separate, it think it would be fairly easy to modify the engine to handle all of the use cases for docker.

Another thing I wanted to comment on is separating docker ignore's into their own front end project.  One of the original decisions behind gitignore.io was to ensure that it only does one thing well.  It would probably make sense to create a dockerignore.io or something in order to make a project that handles docker files.

That being said, I'm all for helping to figure out a way to make docker ignore templates more accessible.

What do you currently do when you're looking for `.dockerignore` templates?

**Comment by joeblau** [comment]
I'm going to turn the gitignore project into a monorepo which should help break up the different parts of this project into a better organizational hierarchy.  After I separate this out, it should be easy to figure out what the dockerignore engine looks like.
