### ISSUE TITLE
old curl script won't work anymore after redirections introduced (https, and toptal.com)

### ISSUE THREAD

**Issue by AlexTelon** [toptal/gitignore.io#496]
## Issue
The recent redirect causes issues to scripts.

### Expected Behavior:
`curl gitignore.io/api/visualstudiocode,python > .gitignore`
I expected this create a .gitignore file filled with gitignore for vscode and python. 

### Actual Behavior:
The file is empty. Nothing is downloaded due to redirection to toptal.
Also note that #480 is also related. Because the redirection to `https://` also causes this issue. 
For example this wont work either (due to missing `https://`):
`curl www.toptal.com/developers/gitignore/api/visualstudiocode,python`

### Solution for users
Adding the [-L flag](https://curl.haxx.se/docs/manpage.html#-L) will make it work again as it will follow the recently introduced redirection.

**Example that works:**
`curl -L gitignore.io/api/visualstudiocode,python > .gitignore`

Note that 'wget' still works as it did before since it seems to follow the redirection by default.

### A change suggestion
It would be great if you could add a check for the user-agent doing the request. If the user agent is some version of curl then you could not do the redirection? That way old scripts will still work. You still do the redirection for everything else which still makes sure the company name is still visible to all eyeballs.

Example user-agent from curl: `'user-agent': 'curl/7.54.0'` from [stack overflow](https://stackoverflow.com/a/51750402/1723886 ).

**Comment by Muqito** [comment]
Or maybe if they could serve the request directly from gitignore.io without a redirect.

Feels kinda wonky to add an exception for curl.

Otherwise it might be turned off if you have other applications such as Postman with default settings to not follow redirects.

**Comment by achwedyk** [comment]
@AlexTelon Thank you for filing the issue and providing the solution for the users.

The [command-line usage documentation](https://docs.gitignore.io/install/command-line) mentions using two flags `-sL` with `curl` - which are: silent mode (`-s`) and following redirects (`-L`).

It was like that even before the project [was migrated to Toptal](https://github.com/toptal/gitignore.io/pull/494) - the documentation snapshot from February 2019 is [available here](https://github.com/joeblau/gitignore.io-docs/blob/52b47d99c822e23fed1f586f2d51926a120ea645/install/command-line.md#git).

Following the redirects or updating the URL are the only solutions we can suggest at the moment.
Due to business requirements, we can't serve the page from gitignore.io directly and redirecting based on the user-agent is not possible with our current setup either.

**Comment by AlexTelon** [comment]
Thanks for the update. I understand that the recent change was not a technical decision.
